server:
  port: 7073
  #servlet:
  #  context-path: /pfr

spring:
  datasource:
    url: jdbc:mysql://192.168.26.132:3306/vdoor?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gosun
    password: video
    druid:
      #druid页面暴露了敏感信息，需要账号访问增加安全性
      stat-view-servlet:
        login-username: admin
        login-password: 123456
  # 上传文件限制
  servlet:
    multipart:
      max-request-size: 110MB
      max-file-size: 100MB
  jackson:
    #格式化返回json中日期的格式
    date-format: yyyy-MM-dd HH:mm:ss
    #北京时区，默认为GMT,会少8个小时
    time-zone:  GMT+8

############################mybatis配置#######################################
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  # #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.gosuncn.pfr.entity
  global-config:
    db-config:
      db-type: mysql
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
    cache-enabled: false

# 日志路径
logging:
  file: ./logs/pfr.log
  level:
    com.gosuncn.pfr: debug #正式环境请改为error

swagger:
  show: true #线上环境应该把接口文档关闭

device:
  #设备心跳频率（秒）
  heart:
    time: 60
  #设备链接超时时间（秒）
  connect:
    out:
      time: 60