server:
  port: 7071
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: booszy
  application:
    name: k-config-server
  cloud:
    config:
      server:
#        git:
#          uri: https://git.coding.net/yirenyishi/springcloud-config-profile
#          searchPaths: '{application}'
        native:
          searchLocations: classpath:/config
eureka:
  client:
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: k-config-server