server:
  port: 8761 #微服务默认端口
eureka:
  datacenter: trmap
  environment: product
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka/
    # 禁止自己向自己注册
    register-with-eureka: false
    fetch-registry: false
spring:
  security:
    basic:
      enabled: true
    user:
      # 管理页面账号密码
      name: root
      password: booszy
